name: api
server:
  rootPath: /api
database:
  driverClass: org.mariadb.jdbc.Driver
  user: root
  password: Banaan
  url: jdbc:mysql://localhost:3306/1919Shop
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
  evictionInterval: 10s
  minIdleTime: 1 minute
logging:
  level: INFO
  loggers:
    "org.hibernate.SQL":
      level: DEBUG
      additive: true
      appenders:
        - type: console
          threshold: WARN
          target: stderr

    "org.hibernate.type":
      level: TRACE
      additive: true
      appenders:
        - type: console
          threshold: WARN
          target: stderr
